mpc_solver_name: aerial_robot_control::mpc_solver::TiltQdServoThrustDistDifferentialSecondOrderMdlMPCSolver
aerial_robot_control_name: aerial_robot_control/nmpc_controller/tilt_mt/servo_thrust_dist_differential_second_order_nmpc


controller:
  nmpc:
    T_samp: 0.01  # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # seconds
    T_step: 0.1  # seconds

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 23   # N
    thrust_min: 0  # N

    a_max: 3.15  # 180 deg + a little bit
    a_min: -3.15

    alpha_velocity_min: -5  # rad/s
    alpha_velocity_max: 5
    thrust_velocity_min: -100  # N/s
    thrust_velocity_max: 100

    # Just for safety, pretty much double what the real state limits are.
    alpha_c_velocity_min: -5  # rad/s
    alpha_c_velocity_max: 5
    thrust_c_velocity_min: -100  # N/s
    thrust_c_velocity_max: 100

    # params for the cost function
    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 600
    Qw_xy: 20
    Qw_z: 20
    Qa: 0
    Qt: 0.1  # t is for thrust
    Qad: 1
    Qtd: 0.0  # t is for thrust
    Qfu: 0.01 # generated body force
    Qtau: 0.01 # generated body torque

    Rtd_c: 0.0001  # thrust rate of change
    Rad_c: 0.01 # arm angular velocity

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_phys_params: false
    is_debug: false
